[package]
name = "clash-config-proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3.0", features = ["rustls"] }
serde = "1.0"
serde_yaml = "0.8"
ring = "0.16.20"

