
port: 8080
token: xxx
sources:
  - https://clash.yml

proxies:
  - name: xxx
    type: http
    server: xxx
    port: xxx

rules:
  - DOMAIN-SUFFIX,xxx

rule-providers:
  reject:
    type: xxx
    behavior: xxx
    url: "xxx"
    path: ./ruleset/xxx.yaml
    interval: 86400
